# Generated by Django 5.0.6 on 2024-06-24 22:45

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(default=django.utils.timezone.now)),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        validators=[accounts.models.validate_passport_number],
                    ),
                ),
                ("bc_number", models.CharField(blank=True, max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[accounts.models.validate_phone_number],
                    ),
                ),
                ("program_of_study", models.CharField(blank=True, max_length=100)),
                ("city_of_birth", models.CharField(blank=True, max_length=100)),
                ("province_of_birth", models.CharField(blank=True, max_length=100)),
                ("province_in_morocco", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=100)),
                (
                    "inscription_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2020/2021", "2020/2021"),
                            ("2021/2022", "2021/2022"),
                            ("2022/2023", "2022/2023"),
                            ("2023/2024", "2023/2024"),
                            ("2024/2025", "2024/2025"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
                (
                    "civil_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Single"),
                            ("M", "Married"),
                            ("W", "Widowed"),
                            ("D", "Divorced"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                (
                    "level_of_study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.levelofstudy",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.university",
                    ),
                ),
            ],
        ),
    ]
